### ISSUE TITLE
Class member function implementation should be in cpp file, header files should contain only class interface, without unneeded details;

### ISSUE THREAD

**Issue by krisjans** [EdgarsMelnalksnis/TXTfileGame#3]
https://github.com/EdgarsMelnalksnis/TXTfileGame/blob/ac62fa5bf0acc4795105936efc5e8b9f2efb249b/formula.h#L30-L47

**Comment by EdgarsMelnalksnis** [comment]
fixed in 755ac064f07d59733b4847bce81968a91c069c1d
